# docker-compose.yml
version: '3'

services:
  chat:
    build: .
    volumes:
    - chat_rooms:/usr/src/app/rooms
    ports:
     - "5000"
    networks:
     - mynet
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat
    networks:
      - mynet
    ports:
      - "4000:4000"
networks:
  mynet:
volumes:
  chat_rooms:
